name: klipy_dart
version: 0.0.1
description: "A client for interacting with the KLIPY API directly in Dart. Supports all the major endpoints such as featured (trending), search, categories, etc."
homepage: https://github.com/flyclops
repository: https://github.com/flyclops/klipy_dart
topics:
  - gif
  - klipy
  - tenor
  - giphy

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^1.6.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.21.4
