name: tenor_dart
version: 0.0.3
description: "A client for interacting with the Tenor API directly in Dart. Supports all the major endpoints such as featured (trending), search, categories, etc."
homepage: https://github.com/flyclops
repository: https://github.com/flyclops/tenor_dart
topics:
  - gif
  - tenor

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^1.5.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.26.3
